package utilities;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import configuration.ReadPropertiesFile;

public class Email extends Reporting{
	
	private static FileWriter filewriter;
	private String email_recipient = "Email_Recipients";
	private String email_flag = "Email";
	
	public String createPowershellFile() {
		String emailFileName = null;
		String mailBody = "Hello\n\n Please find the report of the execution\n\n\n\n ----Its an autogenerated mail. Please do not reply back---- ";
		try {
			emailFileName = System.getProperty("user.dir") + "\\sendEmail.ps1";
			File file = new File(emailFileName);
			filewriter = new FileWriter(file);
			filewriter.write("$SourceDir = \""+extendReportPath+"\\ExtentReport\\*.html\"\n");

			filewriter.write("If (Test-path $SourceDir ){\n"); 
			filewriter.write("$recipients ="+email_recipient+"\n" );
			filewriter.write("Get-ChildItem $SourceDir | Where {-NOT $_.PSIsContainer} | foreach {$_.fullname} | "
					+ "Send-MailMessage -To $recipients -SmtpServer \"txrelay.epsilon.com\" -From \"Test_Automation@epsilon.com\" "
							+ "-Subject \"Automation Test Email\" -Body \""+mailBody+"\"}\n");
			filewriter.close();
		} catch (Exception e) {
			l4jlogger.error("Failed to create testcase file due to exception " + e.getMessage());
		}
	return emailFileName;
	}
	
	public void sendEmail() {
		if(email_flag.contains("Y")) {
		String PSFilePath = createPowershellFile();
        try {
        	String command = "Powershell.exe -executionpolicy Unrestricted -File "+PSFilePath+"";
        	Runtime.getRuntime().exec(command);
			l4jlogger.info("Email Sent");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		}
	}
}